import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Banner from '../components/banner/banner';
import NavBar from '../components/nav/navbar';

import SectionCards from '../components/card/section-cards';
import { getVideos } from '../lib/videos';

console.log({getVideos})

export async function getServerSideProps() {
  const disneyVideos = await getVideos();

  // Pass data to the page via props
  return { props: { disneyVideos } }
}

export default function Home({ disneyVideos }) {
  console.log({disneyVideos});
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="Chris" />
      <Banner
      title="Clifford the red dog"
      subTitle="a very cute dog"
      imgUrl="/static/clifford.webp"
      />

      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large"/>
        <SectionCards title="Disney" videos={disneyVideos} size="medium" />
      </div>

    </div>
  )
}
