import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Banner from '../components/banner/banner';
import NavBar from '../components/nav/navbar';

import SectionCards from '../components/card/section-cards';
import { getVideos, getPopularVideos, getWatchItAgainVideos } from '../lib/videos';
import { verifyToken } from '../lib/utils';

export async function getServerSideProps(context) {
  const token = context.req ? context.req?.cookies.token : null;
  const userId = await verifyToken(token);

  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  const watchItAgainVideos = await getWatchItAgainVideos(userId, token)

  const disneyVideos = await getVideos("disney trailer");
  const travelVideos = await getVideos("travel");
  const eightiesCartoons = await getVideos("80's cartoons");
  const popularVideos = await getPopularVideos("popular");

  // Pass data to the page via props
  return { props: { disneyVideos, travelVideos, eightiesCartoons, popularVideos, watchItAgainVideos } }
}

export default function Home({ disneyVideos, travelVideos, eightiesCartoons, popularVideos, watchItAgainVideos = [] }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <NavBar username="Chris" />
        <Banner
        videoId="4zH5iYM4wJo"
        title="Clifford the red dog"
        subTitle="a very cute dog"
        imgUrl="/static/clifford.webp"
        />

        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney" videos={disneyVideos} size="large"/>
          <SectionCards title="Watch It Again" videos={watchItAgainVideos} size="small" />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards title="80's Cartoons" videos={eightiesCartoons} size="medium" />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </div>

    </div>
  )
}
